# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p07AK-Gmqo4ElzCCydTHBK1R-V-PzDBz
"""

import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("iris.csv")

x= data['species']
y= data['petal_width']
plt.scatter(x, y, marker='^')
plt.scatter(x, y, marker='o')
plt.show()

x= data['sepal_length']
plt.hist(x,facecolor='g')
plt.xlabel('species')
plt.ylabel('sepal_length')
plt.title('Length of Sepal')
plt.grid(True)
plt.show()

import numpy as np  
import pandas as pd  
import matplotlib.pyplot as plt  
# % matplotlib inline 
  
  
# load the dataset 
df = pd.read_csv("iris.csv") 
  
# display 5 rows of dataset 
df.head()    

df.boxplot(by ='species', column =['petal_length'], grid = False)

import seaborn as sns
data = sns.load_dataset('iris')
fig, ax= plt.subplots(figsize=(6,3))
 
# Make boxplot for one group only
sns.violinplot(ax = ax, y=data["sepal_length"] )
#sns.plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("iris.csv")
data.head(5)

x = data['species']
y = data['sepal_length']

plt.bar(x,y)
#plt.xticks(y_pos, objects)
plt.xlabel('Species')
plt.ylabel('Sepal_length')
plt.title('Length of Sepal')

plt.show()

import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("wine.csv")

x= data['Alcohol']
y= data['Phenols']
plt.scatter(x, y, marker='^')
plt.scatter(x, y, marker='o')
plt.show()

x= data['Alcohol']
plt.hist(x,facecolor='b')
plt.xlabel('Percentage_alcohol')
plt.title('Percentage of Alcohol')
plt.grid(True)
plt.show()

import numpy as np  
import pandas as pd  
import matplotlib.pyplot as plt  
# % matplotlib inline 
  
  
# load the dataset 
df = pd.read_csv("wine.csv") 
  
# display 5 rows of dataset 
df.head()    

df.boxplot(by ='Wine', column =['Alcohol'], grid = False)

#import seaborn as sns
#data = sns.load_dataset('wine')
fig, ax= plt.subplots(figsize=(6,3))
 
# Make boxplot for one group only
sns.violinplot(ax = ax, y=data["Flavanoids"] )
#sns.plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("wine.csv")
data.head(5)

x = data['Wine']
y = data['Alcohol']

plt.bar(x,y)
#plt.xticks(y_pos, objects)
plt.xlabel('Wine')
plt.ylabel('Alcohol')
plt.title('Alcohol_Percentage')

plt.show()

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("diabetes.csv")
df.head(5)

x= df['Glucose']
y= df['Pregnancies']
plt.scatter(x, y)
#plt.scatter(x, y, marker='o')
plt.show()

x= df['BloodPressure']
plt.hist(x,facecolor='r')
plt.xlabel('Blood_pressure')
plt.title('Tension_level')
plt.grid(True)
plt.show()

import numpy as np  
import pandas as pd  
import matplotlib.pyplot as plt  
# % matplotlib inline 
  
  
# load the dataset 
df = pd.read_csv("diabetes.csv") 
  
# display 5 rows of dataset 
df.head()    

df.boxplot(by ='Outcome', column =['Glucose'], grid = False)

#import seaborn as sns
#data = sns.load_dataset('iris')
fig, ax= plt.subplots(figsize=(6,3))
 
# Make boxplot for one group only
sns.violinplot(ax = ax, y=df["BMI"] )
#sns.plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("diabetes.csv")
df.head(5)

x = df['Outcome']
y = df['BMI']

plt.bar(x,y)
#plt.xticks(y_pos, objects)
plt.xlabel('Outcome')
plt.ylabel('BMI')
plt.title('Health_info')

plt.show()

